# Generated by Django 4.2.3 on 2024-05-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatments',
            name='possitionInDesignRight',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='photo1',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='about',
            name='photo2',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='teammemebers',
            name='photo',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='photo',
            field=models.TextField(max_length=5000),
        ),
    ]
