# Generated by Django 4.2.3 on 2024-05-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinApp', '0002_treatments_possitionindesignright_alter_about_photo1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
