# Generated by Django 4.2.3 on 2024-05-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinApp', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
